---
- name: install btrfs package (Ubuntu 16.04 or less)
  apt: name=btrfs-tools
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version | float <= 16.04
  tags:
  - boot

- name: install btrfs package (Ubuntu 16.10 or above || Other Distribution)
  apt: name=btrfs-progs
  when: ansible_distribution != 'Ubuntu' or
        (ansible_distribution == 'Ubuntu' and ansible_distribution_version | float >= 16.10)
  tags:
  - boot

- name: install essential packages (this may take a while)
  apt: name="{{ item }}"
  with_items:
  - build-essential
  - debian-installer-launcher
  - libelf-dev
  - libncurses5-dev
  - libssl-dev
  - live-boot
  - unionfs-fuse
  tags:
  - boot

- name: remove unused kernels
  apt:
    name: linux-image-amd64
    state: absent
  failed_when: false
  tags:
  - boot

#- name: install intel-microcode (iso creation = no)
#  apt: name=intel-microcode
#  when: chroot == false
#  tags:
#  - boot

- name: remove intel-microcode (iso creation = yes)
  apt:
    name: intel-microcode
    state: absent
  when: chroot == true
  tags:
  - boot

- name: install ubuntu casper packages (iso creation = yes)
  apt: name="{{ item }}"
  with_items:
  - casper
  - lupin-casper
  when: chroot == true and ansible_distribution == 'Ubuntu'
  tags:
  - boot

- name: create loop module config (iso creation = yes)
  lineinfile:
    path: /etc/modprobe.d/loop.conf
    line: "options loop max_loop=8"
    create: yes
  when: chroot == true
  tags:
  - boot

- name: add modules to initramfs
  lineinfile:
    path: /etc/initramfs-tools/modules
    line: "{{ item }}"
    create: yes
  with_items:
  - btusb
  - loop
  - overlay
  - pwm-lpss
  - pwm-lpss-platform
  - squashfs
  notify:
  - update boot
  tags:
  - boot
