---
- name: install development packages (workaround until ansible 2.3.2 arrives)
  shell: yum install -y '@C Development Tools and Libraries'
  args:
    warn: false
  changed_when: False
  tags:
  - packages

- name: install essential packages (this may take a while)
  package: name="{{ item }}"
  with_items:
  - bc
  - btrfs-progs
  - dracut
  - efibootmgr
  - elfutils-libelf-devel
  - grub2
  - openssl-libs
  - os-prober
  tags:
  - packages

- name: remove unused kernels
  package:
    name: kernel
    state: absent
  failed_when: false
  tags:
  - boot

- name: add dmsquash-live to dracut config (iso creation = yes)
  copy:
    dest: /etc/dracut.conf.d/01-liveos.conf
    owner: root
    group: root
    mode: 0644
    content: |
      hostonly="no"
      add_dracutmodules+=" dmsquash-live "
  when: chroot == true
  notify:
  - update boot
  tags:
  - boot

- name: remove dmsquash-live from dracut config (iso creation = no)
  file:
    path: /etc/dracut.conf.d/01-liveos.conf
    state: absent
  when: chroot == false
  notify:
  - update boot
  tags:
  - boot

- name: add modules to initramfs
  lineinfile:
    path: /etc/dracut.conf
    line: "add_drivers+=\"{{ item }}\""
    create: yes
  with_items:
  - btusb
  - pwm-lpss
  - pwm-lpss-platform
  notify:
  - update boot
  tags:
  - boot