---
- name: set USE flags for packages
  lineinfile:
    path: /etc/portage/package.use
    regexp: "^{{ item.package }}"
    line: "{{ item.package }} {{ item.flags }}"
    create: yes
  with_items:
  - { package: 'sys-firmware/intel-microcode', flags: 'initramfs' }
  tags:
  - boot

- name: install essential packages (this may take a while)
  portage: package="{{ item }}"
  with_items:
  - dev-libs/libelf
  - dev-libs/openssl
  - sys-firmware/intel-microcode
  - sys-fs/btrfs-progs
  - sys-kernel/dracut
  - sys-libs/ncurses
  tags:
  - boot

- name: remove unused kernels
  portage:
    name: sys-kernel/gentoo-sources
    state: absent
  failed_when: false
  tags:
  - boot

- name: add dmsquash-live to dracut config (iso creation = yes)
  copy:
    dest: /etc/dracut.conf.d/01-liveos.conf
    owner: root
    group: root
    mode: 0644
    content: |
      hostonly="no"
      add_dracutmodules+=" dmsquash-live "
  when: chroot == true
  notify:
  - update boot
  tags:
  - boot

- name: remove dmsquash-live from dracut config (iso creation = no)
  file:
    path: /etc/dracut.conf.d/01-liveos.conf
    state: absent
  when: chroot == false
  notify:
  - update boot
  tags:
  - boot

- name: add modules to initramfs
  lineinfile:
    path: /etc/dracut.conf
    line: "add_drivers+=\"{{ item }}\""
    create: yes
  with_items:
  - btusb
  - pwm-lpss
  - pwm-lpss-platform
  notify:
  - update boot
  tags:
  - boot