---
- name: set USE flags for packages
  lineinfile:
    path: /etc/portage/package.use
    regexp: "^{{ item.package }}"
    line: "{{ item.package }} {{ item.flags }}"
    create: yes
  with_items:
  - { package: 'app-laptop/tlp', flags: 'tlp_suggests'}
  - { package: 'app-portage/layman', flags: 'git' }
  tags:
  - power

- name: install essential packages (this may take a while)
  portage: package="{{ item }}"
  with_items:
  - app-portage/layman
  - sys-power/thermald
  notify:
  - enable thermal services
  tags:
  - power
  
- name: setup portage for layman
  lineinfile:
    path: /etc/portage/make.conf
    line: 'source /var/lib/layman/make.conf'
  tags:
  - power
  
- name: install tlp repository
  layman:
    name: tlp
    list_url: 'https://raw.github.com/dywisor/tlp-portage/maint/layman.xml'
  notify:
  - enable thermal services
  tags:
  - power

- name: install tlp
  portage: package=app-laptop/tlp
  tags:
  - power