---
- name: set USE flags for packages
  lineinfile:
    path: /etc/portage/package.use
    regexp: "^{{ item.package }}"
    line: "{{ item.package }} {{ item.flags }}"
    create: yes
  with_items:
  - { package: 'sys-fs/squashfs-tools', flags: 'lz4 lzma lzo xz' }
  tags:
  - iso

- name: install essential packages (this may take a while)
  portage: package="{{ item }}"
  with_items:
  - dev-libs/libisoburn
  - sys-fs/dosfstools
  - sys-fs/squashfs-tools
  tags:
  - iso