---
- name: set USE flags for packages
  lineinfile:
    path: /etc/portage/package.use
    regexp: "^{{ item.package }}"
    line: "{{ item.package }} {{ item.flags }}"
    create: yes
  with_items:
  - { package: 'media-plugins/gst-plugins-meta', flags: 'aac alsa cdda flac mp3 mpeg ogg pulseaudio vaapi' }
  - { package: 'media-sound/pulseaudio', flags: 'alsa alsa-plugin bluetooth dbus systemd udev' }
  tags:
  - audio

- name: install essential packages (this may take a while)
  package: package="{{ item }}"
  with_items:
  - media-plugins/gst-plugins-meta
  - media-sound/pulseaudio
  notify:
  - enable thermal services
  tags:
  - audio