---
- name: create efi directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - /var/tmp/bootstrap-iso/new-efi
  - /var/tmp/bootstrap-iso/old-efi
  tags:
  - iso

- name: mount old efi partition
  shell: mount -t vfat -o loop "{{ efi_image.files.0.path }}" /var/tmp/bootstrap-iso/old-efi
  args:
    warn: no
  tags:
  - iso

- name: create and mount new efi partition
  shell: |
    dd if=/dev/zero bs=1M count=128 of="{{ efi_image.files.0.path }}.new"
    mkfs.vfat -n 'ARCHISO_EFI' "{{ efi_image.files.0.path }}.new"
    mount -t vfat -o loop "{{ efi_image.files.0.path }}.new" /var/tmp/bootstrap-iso/new-efi
  args:
    warn: no
  tags:
  - iso

- name: copy necessary content to new-efi
  shell: |
    cp -frv /var/tmp/bootstrap-iso/old-efi/* /var/tmp/bootstrap-iso/new-efi/
    cp -fv "{{ system_kernel.files.0.path }}" /var/tmp/bootstrap-iso/new-efi/efi/*/*vmlinuz*
    cp -fv "{{ system_initrd.files.0.path }}" /var/tmp/bootstrap-iso/new-efi/efi/*/*iso.img
  tags:
  - iso

- name: umount efi partitions
  shell: |
    umount /var/tmp/bootstrap-iso/new-efi
    umount /var/tmp/bootstrap-iso/old-efi
  tags:
  - iso

- name: replace old-efi with new-efi
  shell: mv "{{ efi_image.files.0.path }}.new" "{{ efi_image.files.0.path }}"
  tags:
  - iso

- name: remove efi directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /var/tmp/bootstrap-iso/new-efi
  - /var/tmp/bootstrap-iso/old-efi
  tags:
  - iso