---
- name: install python-selinux
  package: name=libselinux-python
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Fedora' or ansible_distribution == 'RedHat'
  tags:
  - common
  - selinux