---
- name: determine which directory to use for firmware
  find:
    paths:
    - /lib
    - /usr/lib
    recurse: yes
    patterns: firmware
    file_type: directory
  register: brcm_firmware
  tags:
  - common
  - wifi

- name: ensure brcm directory exists
  file:
    path: "{{ brcm_firmware.files.0.path }}/brcm"
    state: directory
  tags:
  - common
  - wifi

- name: copy wifi files
  copy:
    src: "{{ item }}"
    dest: "{{ brcm_firmware.files.0.path }}/brcm/"
    owner: root
    group: root
    mode: 0644
  with_items:
  - files/brcmfmac4356-pcie.bin
  - files/brcmfmac4356-pcie.txt
  tags:
  - common
  - wifi